-- MySQL Script generated by MySQL Workbench
-- Sun Sep 19 19:44:13 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema cool_admin_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema cool_admin_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `cool_admin_db` DEFAULT CHARACTER SET utf8 ;
USE `cool_admin_db` ;

-- -----------------------------------------------------
-- Table `cool_admin_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cool_admin_db`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(250) NULL,
  `last_name` VARCHAR(250) NULL,
  `dob` DATE NULL,
  `gender` TINYINT NULL,
  `email` VARCHAR(250) NULL,
  `password` VARCHAR(250) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cool_admin_db`.`friends`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cool_admin_db`.`friends` (
  `user_id1` INT NOT NULL,
  `user_id2` INT NOT NULL,
  `status` TINYINT NULL,
  `add_notification` TINYINT NULL,
  `accept_notification` TINYINT NULL,
  PRIMARY KEY (`user_id1`, `user_id2`),
  INDEX `fk_users_has_users_users1_idx` (`user_id2` ASC),
  INDEX `fk_users_has_users_users_idx` (`user_id1` ASC),
  CONSTRAINT `fk_users_has_users_users`
    FOREIGN KEY (`user_id1`)
    REFERENCES `cool_admin_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_users_users1`
    FOREIGN KEY (`user_id2`)
    REFERENCES `cool_admin_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `cool_admin_db`.`user1_blocked_user2`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `cool_admin_db`.`user1_blocked_user2` (
  `user_id1` INT NOT NULL,
  `user_id2` INT NOT NULL,
  PRIMARY KEY (`user_id1`, `user_id2`),
  INDEX `fk_users_has_users_users3_idx` (`user_id2` ASC),
  INDEX `fk_users_has_users_users2_idx` (`user_id1` ASC),
  CONSTRAINT `fk_users_has_users_users2`
    FOREIGN KEY (`user_id1`)
    REFERENCES `cool_admin_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_users_users3`
    FOREIGN KEY (`user_id2`)
    REFERENCES `cool_admin_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
