-- MySQL Script generated by MySQL Workbench
-- Wed Sep  8 16:31:52 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema elite_shopper_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema elite_shopper_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `elite_shopper_db` DEFAULT CHARACTER SET utf8 ;
USE `elite_shopper_db` ;

-- -----------------------------------------------------
-- Table `elite_shopper_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elite_shopper_db`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(250) NULL,
  `last_name` VARCHAR(250) NULL,
  `gender` TINYINT NULL,
  `dob` DATE NULL,
  `phone` VARCHAR(12) NULL,
  `email` VARCHAR(45) NULL,
  `password` VARCHAR(250) NULL,
  `city` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elite_shopper_db`.`retailers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elite_shopper_db`.`retailers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(250) NULL,
  `phone` VARCHAR(12) NULL,
  `email` VARCHAR(250) NULL,
  `password` VARCHAR(250) NULL,
  `city` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elite_shopper_db`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elite_shopper_db`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `description` VARCHAR(100) NULL,
  `image_url` VARCHAR(100) NULL,
  `uploaded_on` DATETIME NULL,
  `retailers_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_products_retailers1_idx` (`retailers_id` ASC),
  CONSTRAINT `fk_products_retailers1`
    FOREIGN KEY (`retailers_id`)
    REFERENCES `elite_shopper_db`.`retailers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elite_shopper_db`.`users_has_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elite_shopper_db`.`users_has_products` (
  `users_id` INT NOT NULL,
  `products_id` INT NOT NULL,
  PRIMARY KEY (`users_id`, `products_id`),
  INDEX `fk_users_has_products_products1_idx` (`products_id` ASC),
  INDEX `fk_users_has_products_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_users_has_products_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `elite_shopper_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_products_products1`
    FOREIGN KEY (`products_id`)
    REFERENCES `elite_shopper_db`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
