-- MySQL Script generated by MySQL Workbench
-- Thu Sep 16 21:40:17 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema expense_tracker_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema expense_tracker_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `expense_tracker_db` DEFAULT CHARACTER SET utf8 ;
USE `expense_tracker_db` ;

-- -----------------------------------------------------
-- Table `expense_tracker_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `expense_tracker_db`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(250) NULL,
  `last_name` VARCHAR(250) NULL,
  `email` VARCHAR(250) NULL,
  `password` VARCHAR(250) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `expense_tracker_db`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `expense_tracker_db`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(250) NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_categories_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_categories_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `expense_tracker_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `expense_tracker_db`.`expenses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `expense_tracker_db`.`expenses` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(250) NULL,
  `amount` FLOAT NULL,
  `date` DATE NULL,
  `user_id` INT NOT NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_expenses_users_idx` (`user_id` ASC),
  INDEX `fk_expenses_categories1_idx` (`category_id` ASC),
  CONSTRAINT `fk_expenses_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `expense_tracker_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_expenses_categories1`
    FOREIGN KEY (`category_id`)
    REFERENCES `expense_tracker_db`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
